Task/260032 show modal
AOEpeople/meals pull request #351
Opened 2023-10-02 13:08 UTC by IrisOlfermann

2023-10-17 09:15 UTC, MalibusParty requested changes
hab tristan noch infos für euch mitgeteilt, bei fragen gerne auf ihn zurükkommen

2023-10-23 08:40 UTC, AYAxDesign commented on src/Resources/src/components/dashboard/Day.vue
> +      class="relative grid w-[24px] content-center justify-center  gap-2 rounded-l-[5px] py-[2px] text-center"
@AYAxDesign

2023-10-23 08:40 UTC, AYAxDesign commented on src/Resources/src/components/dashboard/InformationButton.vue
@AYAxDesign

2023-10-23 08:41 UTC, AYAxDesign commented on src/Resources/src/views/ParticipantsListByDay.vue
> +            class="text-s leading- w-2/5 whitespace-nowrap py-4 pl-4 pr-3 font-light">
@AYAxDesign

2023-10-23 08:41 UTC, AYAxDesign commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +            :btn-text="t('combiModal.cancel')"
@AYAxDesign

2023-10-23 08:50 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +const props = defineProps<{
@IrisOlfermann

2023-10-23 08:50 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +const { addWindowHeightListener, removeWindowHeightListener } = useComponentHeights();
@IrisOlfermann

2023-10-23 08:50 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +const { loadShowParticipations, activatePeriodicFetch, disablePeriodicFetch } = getShowParticipations();
@IrisOlfermann

2023-10-23 08:51 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +
@IrisOlfermann

2023-10-23 08:52 UTC, IrisOlfermann commented on src/Resources/src/views/ParticipantsListByDay.vue
> +console.log(props.date)
@IrisOlfermann

2023-10-23 08:59 UTC, IrisOlfermann commented on src/Resources/src/api/getParticipationsByDate.ts
@IrisOlfermann

2023-10-23 13:34 UTC, IrisOlfermann commented on src/Resources/src/api/getParticipationsByDate.ts
> +const listDataState = reactive<ListData>({
Hat sich von selber erledigt, da die Funktionalität von getParticipationsByDate in getPrintableList ergänzt wurde und die Datei getParticipationsByDate danach gelöscht wurde.

2023-10-23 13:36 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +const { loadShowParticipations, activatePeriodicFetch, disablePeriodicFetch } = getShowParticipations();
Wird tatsächlich nicht gebraucht, wurde entfernt.

2023-10-23 13:42 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +  if (doSubmit === true && selectedCombi.value.includes(-1) === false) {
doSubmit wird benötigt zum Schließen des Modalfensters, selectedCombi war noch ein Überbleibsel, das jetzt entfernt wurde.

2023-10-23 14:07 UTC, AYAxDesign commented on src/Resources/src/components/dashboard/Day.vue
> +      class="relative grid w-[24px] content-center justify-center  gap-2 rounded-l-[5px] py-[2px] text-center"
@MalibusParty Leider haben wir die Linter-Konfiguration nicht die, die Fehler markiert / anzeigt.

2023-10-23 14:16 UTC, AYAxDesign commented on src/Resources/src/views/ParticipantsListByDay.vue
☑️ resolved ready for review

2023-10-24 06:54 UTC, MalibusParty commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +            :btn-text="t('combiModal.cancel')"
Ich meinte damit, dass 'Abbrechen' der aktuelle Text ist, der auf dem Button angezeigt wird. Dies entspricht nicht der Funktion, die der Button hat.

2023-10-24 08:58 UTC, MalibusParty requested changes

2023-10-30 08:23 UTC, IrisOlfermann commented on src/Resources/src/api/getPrintableListData.ts
> +    (date !== undefined && date !== null )? `/api/print/participations/${date}` : '/api/print/participations/'
@IrisOlfermann

2023-10-30 08:24 UTC, IrisOlfermann commented on src/Resources/src/api/getPrintableListData.ts
> + * @returns list of participants
@IrisOlfermann

2024-02-13 13:24 UTC, merged