Feature/#259009 participant list
AOEpeople/meals pull request #448
Opened 2024-03-19 08:22 UTC by IrisOlfermann

2024-03-20 15:55 UTC, MalibusParty requested changes

2024-03-20 15:55 UTC, MalibusParty commented on src/Mealz/MealBundle/Controller/ApiController.php
> +            return new JsonResponse('', 404);
Wenn der Request aufgrund eines Fehler fehlschlägt, sollte eine message im Format ['message' => 'Fehlermeldung'] zurückgegeben werden

2024-03-20 15:55 UTC, MalibusParty commented on src/Mealz/MealBundle/Controller/ApiController.php
> +            return new JsonResponse('', 404);
Siehe Kommentar oben

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +export type ListData = [];
Für ein Array muss kein eigener Typ erstellt werden, statt diesem Typ sollte string[] als Typ verwendet werden

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +const listDataState = ref([]);
Hier fehlt die angabe des Typs, es wird nur any erkannt. Dies sollte nicht passieren

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +const listDataState = ref([]);
dieser State wurde als globaler State definiert, wird aber soweit ich das sehen kann nur lokal verwendet. -> Als lokalen State definieren, dann kann das onUnmounted auch entfernt werden

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +        if (undefined === date) {
in JS und TS wird im Gegensatz zu PHP der Vergleichswert hinter die Variable gesetzt: date === undefined

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +    let useParticipationsError = false;
wenn in einer Vue Komponente auf den Wert einer Variable reagiert werden soll, muss diese als reaktive Vue Variable definiert werden (ref(), reactive(), computed(),...) sonst kann es zu unerwartetem Verhalten kommen.

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +function closeParticipantsModal(doSubmit: boolean) {
Wieso existiert ein boolean flag 'doSubmit', wenn es immer false ist?

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +        <IconCancel
Der Cancel-Button ist nicht wie die beiden anderen Elemente der Reihe zentriert
<img width="613" alt="Bildschirmfoto 2024-03-20 um 16 36 22" src="https://github.com/AOEpeople/meals/assets/76796838/8f0cbc41-2942-490a-890a-0e3a08e9e52c">

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +      <DialogPanel
Der Drop-Shadow sollte wie bei anderen Popups dunkel sein

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/misc/FilterInput.vue
> +<template>
die Komponente ist eine abgesteckte Variante einer bestehenden Komponente, die stattdessen verwendet werden könnte. Ersetzt FilterInput durch InputLabel

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/misc/IconCancel.vue
> +const buttonPressed = ref(false);
mit der Variable wird nichts gemacht, sie kann entfernt werden

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/misc/IconCancel.vue
> +<style scoped>
der style wird nicht verwendet, kann entfernt werden

2024-03-20 15:55 UTC, MalibusParty commented on src/Resources/src/components/misc/IconCancel.vue
> +  <XIcon
da nur die Komponente <XIcon /> verwendet wird, kann die gesamte Komponente IconCancel.vue entfernt werden und durch XIcon ersetzt werden

2024-03-22 10:08 UTC, AYAxDesign commented on src/Resources/src/components/misc/FilterInput.vue
> +<template>
Diese Komponente unterscheidet sich optisch zu InputLabel.

2024-03-25 08:26 UTC, IrisOlfermann commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +function closeParticipantsModal(doSubmit: boolean) {
https://github.com/AOEpeople/meals/commit/34b1c2bcf3796603b1d8676d206a02eda735b5b8

2024-03-27 15:55 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +export type ListData = [];
Ich meinte damit, dass an den stellen an denen als Type ListData verwendet wird, ihr das durch string[] ersetzen könnt: useApi<ListData>('xyz') kann genauso mit useApi<string[]>('xyz') geschrieben werden. Da hier der Type nicht mehrere Elemente umfasst, sollte dafür kein neuer Type definiert werden

2024-03-27 15:56 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +const listDataState = ref([]);
hier dann ref<string[]>([]) verwenden und nicht ref<ListData>([])

2024-03-27 15:59 UTC, MalibusParty commented on src/Resources/src/api/getParticipationsByDay.ts
> +const listDataState = ref([]);
damit meinte ich dass ihr den state innerhalb von useParticipationsListData definieren könnt. Damit wird der state lokal und damit wird dann der onUnmounted callback unnötig:
export function useParticipationsListData(date: string) {
  ...
  const listDataState = ref<string[]>([]);
  ...
}

2024-03-28 10:12 UTC, AYAxDesign commented on src/Resources/src/components/dashboard/ParticipantsListModal.vue
> +<template>
Ich konnte diesen Fehler leider nicht reproduzieren. Iris hat aber eine Lösug für das Problem gefunden.

2024-04-10 14:32 UTC, MalibusParty approved these changes

2024-05-14 09:23 UTC, merged